### ISSUE TITLE
Support latest version of analytics-ios

### ISSUE THREAD

**Issue by afestein** [segment-integrations/analytics-ios-integration-mixpanel#14]
I've come across [an issue which has been fixed in later versions of the Segment pod](https://github.com/segmentio/analytics-ios/issues/518) however this pod specifies 3.0 as the only supported version. 

Is there any a possibility of supporting Analytics 3.1.2.?

**Comment by ladanazita** [comment]
3.0 supports version greater than 3.0 and less than 4.0

See https://guides.cocoapods.org/syntax/podfile.html#pod and https://guides.cocoapods.org/using/the-podfile.html for reference.

**Comment by afestein** [comment]
I see, I misinterpreted the `~>` syntax here. Good to know, thanks for the reply.
