### ISSUE TITLE
Running `pod outdated` always shows "Segment-Mixpanel 1.1.0 -> 1.1.0 (latest version 2.9.0-alpha)"

### ISSUE THREAD

**Issue by jawwad** [segment-integrations/analytics-ios-integration-mixpanel#16]
I'm guessing that if the 2.9.0-alpha tag was removed or renamed to 0.9.0-alpha that would fix the issue

**Comment by f2prateek** [comment]
CocoaPods should only show you stable releases (see https://github.com/CocoaPods/search.cocoapods.org/issues/102 and http://blog.cocoapods.org/Release-Versions-Only/ and https://github.com/CocoaPods/Specs/pull/13644#issuecomment-158203106).

If it's not doing that then you can raise an issue with CocoaPods.
