### ISSUE TITLE
Not sending call to Mixpanel because it doesn't respond to applicationDidBecomeActive.

### ISSUE THREAD

**Issue by mattfeury** [segment-integrations/analytics-ios-integration-mixpanel#17]
Hello,

I'm having trouble getting AB tests running on our iOS segment-mixpanel integration. We're seeing the below line in the logs:
```
Not sending call to Mixpanel because it doesn't respond to applicationDidBecomeActive.
```

However, it [appears that](https://mixpanel.com/help/reference/ios#ab-testing) mixpanel utilizes this function to get the latest AB test data. (quoted from that link: "Mixpanel checks for any new experiments asynchronously on applicationDidBecomeActive")

i don't see how AB tests could be working with the current integration. am i missing something?

**Comment by f2prateek** [comment]
All the log is saying that the integration itself is not doing anything for that event.

Mixpanel itself registers with the notification center to receive the event https://github.com/mixpanel/mixpanel-iphone/blob/d9dc2e3556c52584ba3383f963bfa7db96454c40/Mixpanel/Mixpanel.m#L897-L900. There is no Mixpanel API the integration can call.
