### ISSUE TITLE
Settings user traits of anonymous user before alias and identify are called

### ISSUE THREAD

**Issue by arabold** [segment-integrations/analytics-ios-integration-mixpanel#21]
In our app we use install attribution (Branch) which triggers an asynchronous callback shortly after first app launch. In this callback I want to set certain user traits such as `installSource` and `installCampaign`. At this point the user isn't logged in yet and I do not have a valid userId yet.

The code looks somewhat like that (note the `identify:nil`):
```obj-c
// Set user traits so we can segment the user by acquisition channel later
[[SEGAnalytics sharedAnalytics] identify:nil traits:@{
   @"installSource": params[@"~channel"] ? params[@"~channel"] : @"",
   @"installCampaign": params[@"~campaign"] ? params[@"~campaign"] : @"",
   @"installAdGroup": params[@"$marketing_title"] ? params[@"$marketing_title"] : @"",
   @"installAdProvider": @"Branch"
}];
```

Once the user finally logs in I'm calling `alias` and `identify` like this (whereas `[self getUserId]` return our server-side generated user ID):
```obj-c
[[SEGAnalytics sharedAnalytics] alias:[self getUserId]];
[[SEGAnalytics sharedAnalytics] identify:[self getUserId] traits:@{@"createdAt": [NSDate date], @"userId": [self getUserId]}];
```

In cases in which the install attribution callback is invoked _after_ identifying the user everything works as expected. However, in most cases the callback is called _before_ the user logs in. In this case none of the traits get set in MixPanel. Events sent either before or after the `alias` and the `identify` call are tracked and show up as expected though. Only the traits get lost.

I'm trying to figure out where things are going wrong. From my understanding of the Segment SDK itself it should be possible to set the traits this way even before the user is first identified. So is this a bug in the Mixpanel-Segment-Integration?

The versions used are:
```
  - Analytics (3.5.5)
  - Mixpanel (3.0.8):
  - Segment-Mixpanel (1.1.0):
```

**Comment by f2prateek** [comment]
I'm not totally sure where problem could be happening.

Let's ignore the alias piece for a second.

Are you saying that just this call:
```
// Set user traits so we can segment the user by acquisition channel later
[[SEGAnalytics sharedAnalytics] identify:nil traits:@{
   @"installSource": params[@"~channel"] ? params[@"~channel"] : @"",
   @"installCampaign": params[@"~campaign"] ? params[@"~campaign"] : @"",
   @"installAdGroup": params[@"$marketing_title"] ? params[@"$marketing_title"] : @"",
   @"installAdProvider": @"Branch"
}];
```

Does not set any traits in Mixpanel?

**Comment by arabold** [comment]
It's important that I'm doing two steps here:

1. Right after first and initial app start I'm calling `[[SEGAnalytics sharedAnalytics] identify:nil ...]` with the install attribution
2. Then, at a later point, the user logs in and I'm calling `[SEGAnalytics sharedAnalytics] identify:[self getUserI] ...]` to finally identify the user.

The first call to set the install attribution traits works if it happens _after_ the second one. However it does NOT work before when I'm only having an anonymous user and don't know the userId yet. Events are tracked with the user as expected in either case, just the traits aren't. Does this explanation make sense?

**Comment by f2prateek** [comment]
I do understand what you're trying to do, but trying to verify the behaviour of just the first call `identify:nil traits:@{...}`. Do these traits for the anonymous user show up in Mixpanel?

If they do, then it's likely the alias code is at fault and we can debug that further. If not, then it's likely identify code itself is the one with issues.

**Comment by f2prateek** [comment]
Also if you could enable logging and post the logs here or share them with https://segment.com/contact/requests/ that will help us verify what's exactly going on under the hood with your implementation.

**Comment by arabold** [comment]
Actually, I might have identified the issue not being caused by Segment or MixPanel, but by a sneaky little `reset` that seemed to have found it's way in our code somewhere in between the first and the second identify call. Let me dive a little bit deeper and report back. That would have been a very stupid and very shameful bug...

**Comment by arabold** [comment]
Okay, seems I can confirm that this is caused by a `reset` I've overlooked in the code. Guess the reason why this wasn't immediately obvious is that the tracking calls (the events) were showing up correctly for the anonymous user, just the people traits/properties weren't. I'm closing this error report now as this seems to be the expected behavior from what I understand. Thanks for your help, @f2prateek. Sometimes just asking the right questions gets you further.
