### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by gsinghs** [segment-integrations/analytics-ios-integration-mixpanel#27]
I have installed your pod using : pod "Segment-Mixpanel"

And I am tracking events using:
    [[SEGAnalytics sharedAnalytics] track:@"EVENT_NAME"];

**Now my app crashes in Mixpanel lbrary (IN CLASS: Mixpanel.m on line number 482) :**

-                          0x0000000100208e24 __38-[Mixpanel setupAutomaticPushTracking]_block_invoke_2 (Mixpanel.m:482) 
-                       0x000000010022de74 mp_swizzledMethod_4 (MPSwizzler.m:75)

The reason for crash it gives is:
**-[__NSDictionaryI notification]: unrecognized selector sent to instance 0x174e73ec0**

Please fix this asap. The crash is appearing in iOS 10 only and not iOS 9

Thanks!

**Comment by ladanazita** [comment]
Hi @gsinghs - this looks like this is occurring in the native Mixpanel SDK. Could you submit a request through our [contact form](segment.com/contact) with the complete crash logs and a reproducible case?

Thanks!
