### ISSUE TITLE
Integrations don't work!

### ISSUE THREAD

**Issue by alecsechechel** [segment-integrations/analytics-ios-integration-mixpanel#40]
You have cool idea and it looks very nice.

But when I try integrate any tools I have same problem 'Segment-Amplitude/SEGAmplitudeIntegrationFactory.h' file not found same problem for Mixpanel and other services.

I use swift4 and xcode 9.3.1. Do you have any suggestions?

Thanks

**Comment by calvinfo** [comment]
Hey @alecsechechel sorry about the issues here! Do you mind contacting our team via our help portal? They should be able to help you out: https://segment.com/help.

I'm going to close this for now, but that's the best way of contacting us for setup issues going forward!
