### ISSUE TITLE
User's in MixPanel have no userId or id set

### ISSUE THREAD

**Issue by lordcodes** [segment-integrations/analytics-ios-integration-mixpanel#41]
We have an iOS app that has a 'create account' flow and a 'sign in' flow.

**Create account**
```swift
analytics.alias("our_user_guid")
analytics.identify("our_user_guid", traits: traitsMap)
```

**Sign in**
```swift
analytics.identify("our_user_guid", traits: traitsMap)
```

In the Segment debugger, we see the alias and identify calls with the userId correctly set. We also see track events with the userId attached to them correctly.

In the MixPanel user profiles, we see the users created within the app, they have all the traits (name, email etc.) however they have no userId or id attached to them, only the distinctId (MixPanel anonymous Id). Events from the app also have no userId mentioned.

All users/events from our web app using the JS Segment are working correctly in MixPanel and comparing things in the Segment debugger between iOS and web appear completely identical.

I am starting to wonder if there is an issue in the iOS Segment MixPanel integration, or if we are misunderstanding something in the Segment or MixPanel documentation. I would much appreciate some help with this.

Thanks.

**Edit**
From further investigation, the events after creating account (identify calls from above) come through with 'user_id' set to the MixPanel distinctId. This is not our user_guid that we provided to the identify call. This means we cannot search for our user ID in any MixPanel events or user profiles.

After sign in, events come through with 'user_id' set to our user_guid (passed to identify call) and so these events can be searched for with our user_guid.

The alias call that is triggered on account creation just before identify call is resulting in some strange behaviour with regards to user IDs.

**Comment by ladanazita** [comment]
hey @lordcodes , 

Thanks for writing in here. I suggest reaching out to our support team : segment.com/contact for expedited help. They are more versed in the nuances of each tool and how to get the implementation just right.

If a bug/issue with the code is surfaced, happy to dive into that further as well once the support team determines what is occurring.

Thanks!
Ladan

**Comment by lordcodes** [comment]
Okay thanks, I think I have worked out the issues we were having and I think they are within the MixPanel iPhone SDK. So I will be raising the things I have discovered on the MixPanel repository directly.

Therefore, I think this is all good. If I do have any further issues, I will contact the support team as you suggest. Thanks.
