### ISSUE TITLE
Add compatibility to Mixpanel 3.5

### ISSUE THREAD

**Issue by torokzsolt** [segment-integrations/analytics-ios-integration-mixpanel#45]
Mixpanel 3.4.x has a knows issue on iOS 13 (https://github.com/mixpanel/mixpanel-iphone/issues/867), which was addressed by version 3.5.0. Unfortunately, your PodSpec references '~> 3.4.7', which means it is not possible to use Mixpanel 3.5.0 with the current version of your library.
Could you please update it?

**Comment by RetepV** [comment]
I would like to ask the same.

Also, maybe you can update your podspec to not use ~>, but >=. Because Mixpanel seems to use a simple incremental version number. The version after 3.4.9 is not an expected 3.4.10 (which would have worked with ~>), but 3.5.0.

**Comment by RetepV** [comment]
For now, I have solved it like this:

1. Download Segment-Mixpanel.podspec
2. Copy it to where the Podfile is.
3. Edit Segment-Mixpanel.podspec, and change the `~> 3.4.7' to '>= 3.4.7'.
4. Edit the Podfile, and change `pod 'Segment-Mixpanel'` into `pod 'Segment-Mixpanel', :podspec => 'Segment-Mixpanel.podspec'`
5. Run pod update Segment-Mixpanel.

Voila.

I also update Analytics to 3.7.0.

**Comment by RetepV** [comment]
I also verified that Mixpanel pod 3.5.0 works fine with Segment-Mixpanel. For at least the features that we use.

**Comment by abumalick** [comment]
the current version of the library uses 3.5.0

**Comment by torokzsolt** [comment]
You're right. I'm closing this issue as it is solved now.
