### ISSUE TITLE
Not seeing 'mixpanel' in events sent by app

### ISSUE THREAD

**Issue by DougBanksPersonal** [segment-integrations/analytics-ios-integration-mixpanel#6]
Hey there - 
I am bundling Segment-mixpanel with my iOS app through a cocoapod: 
```
  pod 'Segment-Mixpanel'
```
I have enabled Mixpanel integration with this project on the segment dashboard.
We are seeing events show up in segment and those events are propagated through to Mixpanel.

But, according to a conversation I just had with someone at Segment, Mixpanel is not properly bundled with our iOS App because the detailed 'raw' view of events from our app says nothing out Mixpanel integration:

```
{
  "messageId": "048BB5DD-C275-4076-A036-E720F8D2541A",
  "anonymousId": "145E9A34-7294-4ED0-AC2D-A3F6BDC4B5E0",
  "userId": "gamREsG",
  "context": {
    "screen": {
      "width": 414,
      "height": 736
    },
    "device": {
      "manufacturer": "Apple",
      "model": "x86_64",
      "id": "D0A2B4AA-80BE-4401-ABC2-C160AED0BADC",
      "advertisingId": "D397B299-0969-4808-8604-3AC60DC83AE2",
      "adTrackingEnabled": true,
      "type": "ios"
    },
    "os": {
      "name": "iPhone OS",
      "version": "9.2"
    },
    "app": {
      "build": "63",
      "namespace": "com.zeemee.ZeeMee",
      "name": "",
      "version": "1.5"
    },
    "locale": "en-US",
    "library": {
      "name": "analytics-ios",
      "version": "3.0.7"
    },
    "timezone": "America/Los_Angeles",
    "traits": {
      "email": "doug+student03@zeemee.com",
      "typeable_id": "gamREsG",
      "slug": "reggiebarnes",
      "account_type": "Student",
      "name": "3 Doug Barnes"
    },
    "network": {
      "wifi": true,
      "cellular": false,
      "bluetooth": false
    },
    "ip": "24.5.9.198"
  },
  "properties": {
    "applicationDetails": "iOS",
    "applicationType": "native_mobile_app"
  },
  "type": "screen",
  "timestamp": "2016-02-16T23:12:25.171Z",
  "name": "VC_ID_ZMCommunities",
  "integrations": {
    "Segment.io": false
  },
  "writeKey": "PhA2lfToZOHsSZq2p8JgnrfrVC37HcP4",
  "sentAt": "2016-02-16T23:12:24.000Z",
  "receivedAt": "2016-02-16T23:12:25.171Z",
  "originalTimestamp": "2016-02-16T15:12:24-0800"
}
```

According to person-at-segment, if Mixpanel were properly bundled, I'd see something about Mixpanel in the 'integrations' clause above.

So what else do I need to do to?  Is there some kind of extra Mixpanel-specific code I need to add so that my app will send mixpanel-friendly events?

**Comment by f2prateek** [comment]
Yes you need to register the integration https://segment.com/docs/libraries/ios/#bundling-integrations

**Comment by DougBanksPersonal** [comment]
Thanks.

For what it's worth, I have been looking for that information for days.
Like combing through your documentation.  A 15+ email thread with someone
in tech support (Brennan), a live phone call with Brennan, and then a new
email thread with an engineer he passed me off to.

No one has ever mentioned that I need to do anything other than compile
against the pod file.  I even specifically asked what he meant by
"Bundling" an integration: does that mean just compiling against the pod
file. Yes that's what it means.

So... thanks.  Wish I'd found this a few days ago, would've saved a lot of
trouble,

Particularly confusing because Mixpanel seemed to be working (events were
flowing from your server) so it looked like some integrations worked and
others didn't.

Doug

**Comment by DougBanksPersonal** [comment]
Also, on the page where you explain how to integrate google analytics,
there's no mention of adding code.  Just pod file.

**Comment by f2prateek** [comment]
Mixpanel was probably working because if you don't bundle an integration, we'll fall back to our server side integration (https://github.com/segmentio/integration-mixpanel) instead. Similar instructions for GA, it's actually in the docs here https://segment.com/docs/libraries/ios/#bundling-integrations.

**Comment by DougBanksPersonal** [comment]
Yup.  Makes more sense now.

I'd recommend updating the instructions for integration to mention the need
for code changes: right now all that's mentioned in Podfile changes.
[image: Inline image 1]

Also, I made the code changes as described in the doc you referenced.  I am
now seeing Google Analytics and Mixpanel in the 'integration' clause of
events in debugger:

{ "messageId": "xxx", "anonymousId": "xxx", "context": { "screen": { "width"
: 414, "height": 736 }, "device": { "manufacturer": "Apple", "model":
"x86_64", "id": "xxx", "advertisingId":
"52F1B586-6C6E-4CA6-ABCA-268809A06B02", "adTrackingEnabled": true, "type":
"ios" }, "os": { "name": "iPhone OS", "version": "9.3" }, "app": { "build":
"63", "namespace": "com.zeemee.ZeeMee", "name": "", "version": "1.5" },
"locale": "en-US", "library": { "name": "analytics-ios", "version": "3.0.7"
}, "timezone": "America/Los_Angeles", "traits": {}, "network": { "wifi":
true, "cellular": false, "bluetooth": false }, "ip": "24.5.9.198" },
"properties": { "applicationDetails": "iOS", "applicationType":
"native_mobile_app" }, "type": "screen", "timestamp":
"2016-02-17T01:09:02.129Z", "name": "VC_ID_ZMSearch", "integrations": {
"Segment.io": false, "Google Analytics": false, "Mixpanel": false },
"writeKey": "xxx", "sentAt": "2016-02-17T01:09:01.000Z", "receivedAt":
"2016-02-17T01:09:02.129Z", "originalTimestamp": "2016-02-16T17:09:01-0800"
}

However, I am still not seeing any events showing up in Google Analytics.

Any ideas what's going wrong there?
