### ISSUE TITLE
Crash at `-[SEGAnalytics invocationForSelector:arguments:]`

### ISSUE THREAD

**Issue by betzerra** [segment-integrations/analytics-ios-integration-mixpanel#7]
Got a crash at `-[SEGAnalytics invocationForSelector:arguments:]` possibly related with https://github.com/segmentio/analytics-ios/pull/505

Is latest release (1.0.3) using `analytics-ios 3.0.6`?

**Comment by f2prateek** [comment]
You should pin your dependencies manually instead of relying on the version provided by the integrations.
